# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/shin/ultra96v2/tfacc/syn/tfacc_pin.xdc

# IP: /home/shin/ultra96v2/tfacc/ip/ila_0/ila_0.xci
#set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] -quiet

# IP: /home/shin/ultra96v2/tfacc/ip/rdbuf32k/rdbuf32k.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rdbuf32k || ORIG_REF_NAME==rdbuf32k} -quiet] -quiet

# IP: /home/shin/ultra96v2/tfacc/ip/rdbuf16k/rdbuf16k.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rdbuf16k || ORIG_REF_NAME==rdbuf16k} -quiet] -quiet

# IP: /home/shin/ultra96v2/tfacc/ip/rdbuf8k/rdbuf8k.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rdbuf8k || ORIG_REF_NAME==rdbuf8k} -quiet] -quiet

# IP: /home/shin/ultra96v2/tfacc/ip/rdbuf2k/rdbuf2k.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rdbuf2k || ORIG_REF_NAME==rdbuf2k} -quiet] -quiet

# IP: /home/shin/ultra96v2/tfacc/ip/axi_ic/axi_ic.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_ic || ORIG_REF_NAME==axi_ic} -quiet] -quiet

# IP: /home/shin/ultra96v2/tfacc/ip/dpram64kB/dpram64kB.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpram64kB || ORIG_REF_NAME==dpram64kB} -quiet] -quiet

# IP: /home/shin/ultra96v2/tfacc/ip/axi_apb_bridge_0/axi_apb_bridge_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_apb_bridge_0 || ORIG_REF_NAME==axi_apb_bridge_0} -quiet] -quiet

# Block Designs: /home/shin/ultra96v2/tfacc/ip/project_1/project_1.srcs/sources_1/bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: /home/shin/ultra96v2/tfacc/ip/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==design_1_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: /home/shin/ultra96v2/tfacc/ip/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_tfacc_memif_0_0/design_1_tfacc_memif_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_tfacc_memif_0_0 || ORIG_REF_NAME==design_1_tfacc_memif_0_0} -quiet] -quiet

# IP: /home/shin/ultra96v2/tfacc/ip/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_tfacc_cpu_v1_0_0_0/design_1_tfacc_cpu_v1_0_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_tfacc_cpu_v1_0_0_0 || ORIG_REF_NAME==design_1_tfacc_cpu_v1_0_0_0} -quiet] -quiet

# IP: /home/shin/ultra96v2/tfacc/ip/dpram64kB/dpram64kB.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpram64kB || ORIG_REF_NAME==dpram64kB} -quiet] -quiet

# IP: /home/shin/ultra96v2/tfacc/ip/axi_apb_bridge_0/axi_apb_bridge_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_apb_bridge_0 || ORIG_REF_NAME==axi_apb_bridge_0} -quiet] -quiet

# IP: /home/shin/ultra96v2/tfacc/ip/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_rst_ps8_0_100M_0/design_1_rst_ps8_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_ps8_0_100M_0 || ORIG_REF_NAME==design_1_rst_ps8_0_100M_0} -quiet] -quiet

# IP: /home/shin/ultra96v2/tfacc/ip/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/design_1_smartconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_smartconnect_0_0 || ORIG_REF_NAME==design_1_smartconnect_0_0} -quiet] -quiet

# Block Designs: /home/shin/ultra96v2/tfacc/ip/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/bd_48ac.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/shin/ultra96v2/tfacc/ip/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_0/bd_48ac_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/shin/ultra96v2/tfacc/ip/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/shin/ultra96v2/tfacc/ip/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_2/bd_48ac_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/shin/ultra96v2/tfacc/ip/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_3/bd_48ac_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/shin/ultra96v2/tfacc/ip/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_4/bd_48ac_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/shin/ultra96v2/tfacc/ip/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_5/bd_48ac_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/shin/ultra96v2/tfacc/ip/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_6/bd_48ac_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/shin/ultra96v2/tfacc/ip/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_7/bd_48ac_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/shin/ultra96v2/tfacc/ip/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_8/bd_48ac_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/shin/ultra96v2/tfacc/ip/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_9/bd_48ac_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/shin/ultra96v2/tfacc/ip/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_10/bd_48ac_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/shin/ultra96v2/tfacc/ip/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_11/bd_48ac_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/shin/ultra96v2/tfacc/ip/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_12/bd_48ac_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/shin/ultra96v2/tfacc/ip/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_ps8_0_axi_periph_1/design_1_ps8_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ps8_0_axi_periph_1 || ORIG_REF_NAME==design_1_ps8_0_axi_periph_1} -quiet] -quiet

# IP: /home/shin/ultra96v2/tfacc/ip/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ds_0 || ORIG_REF_NAME==design_1_auto_ds_0} -quiet] -quiet

# IP: /home/shin/ultra96v2/tfacc/ip/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# XDC: /home/shin/ultra96v2/tfacc/ip/ila_0/ila_0_ooc.xdc

# XDC: /home/shin/ultra96v2/tfacc/ip/rdbuf32k/rdbuf32k_ooc.xdc

# XDC: /home/shin/ultra96v2/tfacc/ip/rdbuf16k/rdbuf16k_ooc.xdc

# XDC: /home/shin/ultra96v2/tfacc/ip/rdbuf8k/rdbuf8k_ooc.xdc

# XDC: /home/shin/ultra96v2/tfacc/ip/rdbuf2k/rdbuf2k_ooc.xdc

# XDC: /home/shin/ultra96v2/tfacc/ip/axi_ic/axi_ic_impl_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_ic || ORIG_REF_NAME==axi_ic} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/shin/ultra96v2/tfacc/ip/axi_ic/axi_ic_ooc.xdc

# XDC: /home/shin/ultra96v2/tfacc/ip/axi_ic/axi_ic_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_ic || ORIG_REF_NAME==axi_ic} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/shin/ultra96v2/tfacc/ip/dpram64kB/dpram64kB_ooc.xdc

# XDC: /home/shin/ultra96v2/tfacc/ip/axi_apb_bridge_0/axi_apb_bridge_0_ooc.xdc

# XDC: /home/shin/ultra96v2/tfacc/ip/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: /home/shin/ultra96v2/tfacc/ip/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==design_1_zynq_ultra_ps_e_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/shin/ultra96v2/tfacc/ip/ila_0/ila_0_ooc.xdc

# XDC: /home/shin/ultra96v2/tfacc/ip/rdbuf32k/rdbuf32k_ooc.xdc

# XDC: /home/shin/ultra96v2/tfacc/ip/rdbuf16k/rdbuf16k_ooc.xdc

# XDC: /home/shin/ultra96v2/tfacc/ip/rdbuf8k/rdbuf8k_ooc.xdc

# XDC: /home/shin/ultra96v2/tfacc/ip/rdbuf2k/rdbuf2k_ooc.xdc

# XDC: /home/shin/ultra96v2/tfacc/ip/axi_ic/axi_ic_impl_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_ic || ORIG_REF_NAME==axi_ic} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/shin/ultra96v2/tfacc/ip/axi_ic/axi_ic_ooc.xdc

# XDC: /home/shin/ultra96v2/tfacc/ip/axi_ic/axi_ic_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_ic || ORIG_REF_NAME==axi_ic} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/shin/ultra96v2/tfacc/ip/dpram64kB/dpram64kB_ooc.xdc

# XDC: /home/shin/ultra96v2/tfacc/ip/axi_apb_bridge_0/axi_apb_bridge_0_ooc.xdc

# XDC: /home/shin/ultra96v2/tfacc/ip/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_rst_ps8_0_100M_0/design_1_rst_ps8_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_ps8_0_100M_0 || ORIG_REF_NAME==design_1_rst_ps8_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/shin/ultra96v2/tfacc/ip/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_rst_ps8_0_100M_0/design_1_rst_ps8_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_ps8_0_100M_0 || ORIG_REF_NAME==design_1_rst_ps8_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/shin/ultra96v2/tfacc/ip/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/ooc.xdc

# XDC: /home/shin/ultra96v2/tfacc/ip/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/shin/ultra96v2/tfacc/ip/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/shin/ultra96v2/tfacc/ip/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_5/bd_48ac_s00a2s_0_ooc.xdc

# XDC: /home/shin/ultra96v2/tfacc/ip/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_6/bd_48ac_sarn_0_ooc.xdc

# XDC: /home/shin/ultra96v2/tfacc/ip/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_7/bd_48ac_srn_0_ooc.xdc

# XDC: /home/shin/ultra96v2/tfacc/ip/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_8/bd_48ac_sawn_0_ooc.xdc

# XDC: /home/shin/ultra96v2/tfacc/ip/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_9/bd_48ac_swn_0_ooc.xdc

# XDC: /home/shin/ultra96v2/tfacc/ip/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_10/bd_48ac_sbn_0_ooc.xdc

# XDC: /home/shin/ultra96v2/tfacc/ip/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_11/bd_48ac_m00s2a_0_ooc.xdc

# XDC: /home/shin/ultra96v2/tfacc/ip/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_ds_0 || ORIG_REF_NAME==design_1_auto_ds_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/shin/ultra96v2/tfacc/ip/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0_ooc.xdc

# XDC: /home/shin/ultra96v2/tfacc/ip/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc

# XDC: /home/shin/ultra96v2/tfacc/ip/project_1/project_1.srcs/sources_1/bd/design_1/design_1_ooc.xdc
